/**
 * Pure tool metadata for the extension — no SvelteKit, no WASM, no Svelte
 * component imports. This mirrors src/tools/list.ts but is safe to bundle
 * inside a browser extension context.
 *
 * When adding a new tool to the main app, add a matching entry here.
 */

export interface ExtToolConfig {
  slug: string;
  title: string;
  description: string;
  /** Tailwind text-color class used for the tool icon */
  color: string;
  category: 'essentials' | 'conversion' | 'pdf-management' | 'security';
  keywords?: string[];
  /** Lucide icon name (kebab-case). Used to dynamically render the icon. */
  iconName: string;
}

export const CATEGORY_LABELS: Record<ExtToolConfig['category'], string> = {
  essentials: 'Essentials',
  conversion: 'Conversion',
  'pdf-management': 'Management',
  security: 'Security',
};

const tools: ExtToolConfig[] = [
  {
    slug: 'merge-pdf',
    title: 'Merge PDF',
    description: 'Combine multiple PDF files into one single document.',
    category: 'essentials',
    color: 'text-indigo-500',
    iconName: 'file-stack',
    keywords: ['merge pdf', 'combine pdf', 'pdf merger'],
  },
  {
    slug: 'multi-pdf',
    title: 'PDF Multi-Tool',
    description: 'Upload, rearrange, rotate, and export multiple PDF pages.',
    category: 'essentials',
    color: 'text-teal-600',
    iconName: 'file-minus-2',
    keywords: ['pdf multi-tool', 'pdf page manager', 'rearrange pdf pages'],
  },
  {
    slug: 'split-pdf',
    title: 'Split PDF',
    description: 'Extract pages, split ranges, or divide your PDF into multiple files.',
    category: 'essentials',
    color: 'text-pink-500',
    iconName: 'copy',
    keywords: ['split pdf', 'extract pdf pages', 'pdf splitter'],
  },
  {
    slug: 'compress-pdf',
    title: 'Compress PDF',
    description: 'Reduce PDF file size while maintaining quality.',
    category: 'essentials',
    color: 'text-yellow-500',
    iconName: 'zap',
    keywords: ['compress pdf', 'reduce pdf size', 'pdf compressor'],
  },
  {
    slug: 'img-to-pdf',
    title: 'Image to PDF',
    description: 'Convert images (JPG, PNG, BMP, TIFF) to PDF instantly.',
    category: 'conversion',
    color: 'text-orange-500',
    iconName: 'image',
    keywords: ['image to pdf', 'jpg to pdf', 'png to pdf'],
  },
  {
    slug: 'pdf-to-img',
    title: 'PDF to Image',
    description: 'Convert PDF pages into high-quality images.',
    category: 'conversion',
    color: 'text-blue-500',
    iconName: 'bookmark',
    keywords: ['pdf to image', 'pdf to jpg', 'pdf to png'],
  },
  {
    slug: 'encrypt-pdf',
    title: 'Encrypt PDF',
    description: 'Protect your PDF with AES password encryption.',
    category: 'security',
    color: 'text-green-500',
    iconName: 'lock',
    keywords: ['encrypt pdf', 'password protect pdf', 'secure pdf'],
  },
  {
    slug: 'decrypt-pdf',
    title: 'Decrypt PDF',
    description: 'Remove password protection from your PDF.',
    category: 'security',
    color: 'text-green-500',
    iconName: 'unlock',
    keywords: ['decrypt pdf', 'remove password from pdf', 'unlock pdf'],
  },
  {
    slug: 'rotate-pdf',
    title: 'Rotate PDF',
    description: 'Rotate PDF pages to the correct orientation.',
    category: 'pdf-management',
    color: 'text-purple-500',
    iconName: 'rotate-cw',
    keywords: ['rotate pdf', 'rotate pdf pages', 'pdf rotation'],
  },
  {
    slug: 'organize-pdf',
    title: 'Organize PDF',
    description: 'Drag-and-drop interface to reorder PDF pages.',
    category: 'pdf-management',
    color: 'text-purple-500',
    iconName: 'move',
    keywords: ['organize pdf', 'rearrange pdf pages', 'reorder pdf'],
  },
  {
    slug: 'extract-pages',
    title: 'Extract PDF Pages',
    description: 'Select and extract specific pages into a new PDF.',
    category: 'pdf-management',
    color: 'text-pink-500',
    iconName: 'scissors',
    keywords: ['extract pdf pages', 'pdf page extractor'],
  },
  {
    slug: 'crop-pdf',
    title: 'Crop PDF',
    description: 'Crop PDF pages to remove unwanted areas.',
    category: 'pdf-management',
    color: 'text-red-500',
    iconName: 'crop',
    keywords: ['crop pdf', 'trim pdf'],
  },
  {
    slug: 'edit-pdf',
    title: 'Edit PDF',
    description: 'Add and edit text, images, and annotations.',
    category: 'pdf-management',
    color: 'text-blue-500',
    iconName: 'edit-3',
    keywords: ['edit pdf', 'pdf editor', 'add text to pdf'],
  },
  {
    slug: 'bookmark-pdf',
    title: 'Bookmark PDF',
    description: 'Add, edit, and manage bookmarks for easy navigation.',
    category: 'pdf-management',
    color: 'text-blue-500',
    iconName: 'file',
    keywords: ['bookmark pdf', 'add bookmarks to pdf'],
  },
  {
    slug: 'add-page-no-pdf',
    title: 'Add Page Numbers',
    description: 'Add page numbers with customizable font and position.',
    category: 'pdf-management',
    color: 'text-blue-500',
    iconName: 'highlighter',
    keywords: ['add page numbers to pdf', 'page numbering'],
  },
  {
    slug: 'add-watermark-pdf',
    title: 'Add Watermark',
    description: 'Add custom text or image watermarks to your PDF.',
    category: 'pdf-management',
    color: 'text-blue-500',
    iconName: 'wand',
    keywords: ['add watermark to pdf', 'pdf watermark'],
  },
  {
    slug: 'delete-pages',
    title: 'Delete PDF Pages',
    description: 'Remove unwanted pages from your PDF.',
    category: 'pdf-management',
    color: 'text-pink-500',
    iconName: 'text',
    keywords: ['delete pdf pages', 'remove pages from pdf'],
  },
  {
    slug: 'header-footer',
    title: 'Add Header & Footer',
    description: 'Add professional headers and footers to your PDF.',
    category: 'pdf-management',
    color: 'text-blue-500',
    iconName: 'layout-template',
    keywords: ['add header footer to pdf'],
  },
  {
    slug: 'background-color',
    title: 'Change Background Color',
    description: 'Change the background color of PDF pages.',
    category: 'pdf-management',
    color: 'text-blue-500',
    iconName: 'paint-bucket',
    keywords: ['change pdf background color'],
  },
  {
    slug: 'remove-annotations',
    title: 'Remove Annotations',
    description: 'Delete comments, highlights, and markup from your PDF.',
    category: 'pdf-management',
    color: 'text-red-500',
    iconName: 'trash-2',
    keywords: ['remove annotations from pdf', 'delete pdf comments'],
  },
  {
    slug: 'remove-blank-pages',
    title: 'Remove Blank Pages',
    description: 'Automatically detect and remove blank pages.',
    category: 'pdf-management',
    color: 'text-red-500',
    iconName: 'book-minus',
    keywords: ['remove blank pages from pdf'],
  },
  {
    slug: 'extract-images',
    title: 'Extract Images from PDF',
    description: 'Extract all images from your PDF into separate files.',
    category: 'pdf-management',
    color: 'text-green-500',
    iconName: 'eye',
    keywords: ['extract images from pdf'],
  },
  {
    slug: 'txt-to-pdf',
    title: 'Text to PDF',
    description: 'Convert plain text files into PDF format.',
    category: 'conversion',
    color: 'text-green-500',
    iconName: 'file-text',
    keywords: ['text to pdf', 'txt to pdf'],
  },
  {
    slug: 'pdf-to-docx',
    title: 'PDF to Docx',
    description: 'Convert PDF files to editable Word documents.',
    category: 'conversion',
    color: 'text-green-500',
    iconName: 'layers',
    keywords: ['pdf to docx', 'pdf to word'],
  },
  {
    slug: 'pdf-to-excel',
    title: 'PDF to Excel',
    description: 'Convert PDF tables into editable Excel spreadsheets.',
    category: 'conversion',
    color: 'text-green-500',
    iconName: 'maximize-2',
    keywords: ['pdf to excel', 'pdf table to spreadsheet'],
  },
  {
    slug: 'pdf-for-ai',
    title: 'PDF for AI',
    description: 'Optimize and clean PDFs for AI processing.',
    category: 'pdf-management',
    color: 'text-yellow-500',
    iconName: 'refresh-cw',
    keywords: ['pdf for ai', 'optimize pdf for ai'],
  },
  {
    slug: 'ocr-pdf',
    title: 'OCR PDF',
    description: 'Convert scanned PDFs into searchable text with OCR.',
    category: 'conversion',
    color: 'text-green-500',
    iconName: 'scan-text',
    keywords: ['ocr pdf', 'optical character recognition'],
  },
  {
    slug: 'view-metadata',
    title: 'View PDF Metadata',
    description: 'View author, creation date, and embedded properties.',
    category: 'pdf-management',
    color: 'text-blue-500',
    iconName: 'info',
    keywords: ['view pdf metadata', 'pdf properties viewer'],
  },
  {
    slug: 'edit-metadata',
    title: 'Edit PDF Metadata',
    description: 'Update author, title, and custom PDF properties.',
    category: 'pdf-management',
    color: 'text-blue-500',
    iconName: 'settings',
    keywords: ['edit pdf metadata', 'modify pdf properties'],
  },
  {
    slug: 'reverse-pages',
    title: 'Reverse PDF Pages',
    description: 'Reverse the order of pages in your PDF.',
    category: 'pdf-management',
    color: 'text-purple-500',
    iconName: 'arrow-down-up',
    keywords: ['reverse pdf pages', 'flip pdf page order'],
  },
  {
    slug: 'pdf-to-text',
    title: 'PDF to Text',
    description: 'Extract plain text from your PDF with high accuracy.',
    category: 'conversion',
    color: 'text-green-500',
    iconName: 'align-left',
    keywords: ['pdf to text', 'extract text from pdf'],
  },
  {
    slug: 'fix-page-size',
    title: 'Fix PDF Page Size',
    description: 'Standardize PDF page dimensions for consistent printing.',
    category: 'pdf-management',
    color: 'text-blue-500',
    iconName: 'layout-template',
    keywords: ['fix pdf page size', 'standardize pdf dimensions'],
  },
  {
    slug: 'linearize-pdf',
    title: 'Linearize PDF',
    description: 'Optimize your PDF for fast web viewing.',
    category: 'pdf-management',
    color: 'text-yellow-500',
    iconName: 'gauge',
    keywords: ['linearize pdf', 'optimize pdf for web'],
  },
  {
    slug: 'page-dimensions',
    title: 'View Page Dimensions',
    description: 'View the dimensions of each page in your PDF.',
    category: 'pdf-management',
    color: 'text-blue-500',
    iconName: 'info',
    keywords: ['view page dimensions', 'pdf page size viewer'],
  },
  {
    slug: 'deskew-pdf',
    title: 'Deskew PDF',
    description: 'Automatically correct skewed or misaligned PDF pages.',
    category: 'pdf-management',
    color: 'text-red-500',
    iconName: 'crop',
    keywords: ['deskew pdf', 'correct skewed pages'],
  },
  {
    slug: 'validate-signature-pdf',
    title: 'Validate PDF Signature',
    description: 'Verify the authenticity of digital signatures.',
    category: 'security',
    color: 'text-green-500',
    iconName: 'lock',
    keywords: ['validate pdf signature', 'verify digital signature'],
  },
];

export { tools as toolList };

export const toolsByCategory = tools.reduce<Record<string, ExtToolConfig[]>>(
  (acc, tool) => {
    (acc[tool.category] ??= []).push(tool);
    return acc;
  },
  {},
);
