import {
  IconAddressBook,
  IconAlertSquareRounded,
  IconAward,
  IconBarcode,
  IconBuilding,
  IconCalendarEvent,
  IconChartBar,
  IconChartLine,
  IconChartPie,
  IconClipboardList,
  IconCode,
  IconColumns,
  IconFile,
  IconFileInvoice,
  IconFileText,
  IconH1,
  IconId,
  IconLayoutCards,
  IconList,
  IconListCheck,
  IconListDetails,
  IconListNumbers,
  IconMail,
  IconNews,
  IconNumbers,
  IconPackage,
  IconPageBreak,
  IconPhoto,
  IconPilcrow,
  IconPresentation,
  IconProgress,
  IconQrcode,
  IconQuote,
  IconReceipt,
  IconReceipt2,
  IconSchool,
  IconSeparator,
  IconSignature,
  IconSpacingVertical,
  IconTable,
  IconTags,
  IconTextCaption,
  IconTicket,
  IconTimeline,
  IconTypography,
  IconUserCircle,
  type Icon,
} from "@tabler/icons-svelte";
import type { BlockType } from "./model/types";

export const BLOCK_ICONS: Record<BlockType, Icon> = {
  title: IconTypography,
  heading: IconH1,
  paragraph: IconPilcrow,
  quote: IconQuote,
  bullets: IconList,
  numbered: IconListNumbers,
  checklist: IconListCheck,
  code: IconCode,
  finePrint: IconTextCaption,
  divider: IconSeparator,
  spacer: IconSpacingVertical,
  pageBreak: IconPageBreak,
  columns: IconColumns,
  card: IconLayoutCards,
  callout: IconAlertSquareRounded,
  letterhead: IconBuilding,
  addresses: IconAddressBook,
  table: IconTable,
  keyValue: IconListDetails,
  totals: IconReceipt,
  signature: IconSignature,
  stats: IconNumbers,
  progress: IconProgress,
  barChart: IconChartBar,
  lineChart: IconChartLine,
  pieChart: IconChartPie,
  timeline: IconTimeline,
  badges: IconTags,
  image: IconPhoto,
  qr: IconQrcode,
  barcode: IconBarcode,
};

export const PRESET_ICONS: Record<string, Icon> = {
  blank: IconFile,
  "invoice-classic": IconFileInvoice,
  "invoice-modern": IconReceipt2,
  quote: IconFileText,
  receipt: IconReceipt2,
  "business-letter": IconMail,
  resume: IconUserCircle,
  "cover-letter": IconId,
  proposal: IconPresentation,
  report: IconChartBar,
  "meeting-minutes": IconClipboardList,
  certificate: IconAward,
  ticket: IconTicket,
  "packing-slip": IconPackage,
  "lesson-plan": IconSchool,
  "press-release": IconNews,
  "event-agenda": IconCalendarEvent,
};
