import { b } from "./blocks";
import type { Block, CreatorDoc, DocSettings } from "./types";

export type PresetGroup = "Business" | "Work" | "Personal" | "Events";

export interface Preset {
  id: string;
  name: string;
  description: string;
  group: PresetGroup;
  theme: string;
  settings?: Partial<DocSettings>;
  data?: Record<string, string>;
  blocks: () => Block[];
}

export const DEFAULT_SETTINGS: DocSettings = {
  size: "A4",
  orientation: "portrait",
  margin: "normal",
  header: { enabled: false, left: "", right: "" },
  footer: { enabled: false, left: "", pageNumbers: true },
  watermark: { enabled: false, text: "DRAFT" },
};

const footer = (left: string): Partial<DocSettings> => ({ footer: { enabled: true, left, pageNumbers: true } });

export const PRESETS: Preset[] = [
  {
    id: "blank",
    name: "Blank page",
    description: "Start from a heading and a paragraph",
    group: "Business",
    theme: "orbit",
    blocks: () => [b("heading", { text: "Untitled document", level: 1 }), b("paragraph", { text: "Start writing, or add blocks from the library." })],
  },
  {
    id: "invoice-classic",
    name: "Invoice",
    description: "Line items, totals and payment details",
    group: "Business",
    theme: "professional",
    data: { company: "Northwind Studio", client: "Harbour & Co.", number: "2026-042", date: "13 Sep 2026", due: "27 Sep 2026" },
    settings: footer("{{company}} · Invoice #{{number}}"),
    blocks: () => [
      b("letterhead", { brand: "{{company}}", tagline: "Brand and web design", details: "hello@northwind.studio\n+44 20 7946 0958\nnorthwind.studio" }),
      b("title", { eyebrow: "Invoice", title: "#{{number}}", subtitle: "" }),
      b("addresses"),
      b("keyValue", { items: [{ label: "Issued", value: "{{date}}" }, { label: "Due", value: "{{due}}" }, { label: "Currency", value: "USD" }], columns: 2 }),
      b("table"),
      b("totals"),
      b("callout", { title: "Payment details", body: "Bank transfer to IBAN GB29 NWBK 6016 1331 9268 19, reference {{number}}.", tone: "neutral" }),
      b("finePrint", { text: "Payment is due within 14 days. Late payments may incur a 2% monthly fee." }),
    ],
  },
  {
    id: "invoice-modern",
    name: "Modern invoice",
    description: "Bold total, QR code to pay",
    group: "Business",
    theme: "modern",
    data: { company: "Pixel & Pine", client: "Acme Robotics", number: "INV-1187", date: "13 Sep 2026", due: "13 Oct 2026", total: "$12,480" },
    blocks: () => [
      b("columns", { left: "**{{company}}**\nProduct design partners", right: "Invoice {{number}}\nIssued {{date}}\nDue {{due}}", ratio: "1:1" }),
      b("title", { eyebrow: "Amount due", title: "{{total}}", subtitle: "Billed to {{client}}" }),
      b("table", {
        columns: ["Service", "Hours", "Rate", "Amount"],
        rows: [["Discovery workshop", "12", "$160", "$1,920"], ["UX and interface design", "48", "$160", "$7,680"], ["Design system handover", "18", "$160", "$2,880"]],
        striped: false,
      }),
      b("totals", { items: [{ label: "Subtotal", value: "$12,480" }, { label: "Tax", value: "$0" }], totalLabel: "Total", total: "{{total}}" }),
      b("divider", { variant: "dashed" }),
      b("qr", { data: "https://pay.example.com/{{number}}", caption: "Scan to pay online", size: 80 }),
      b("finePrint", { text: "Thank you for working with us." }),
    ],
  },
  {
    id: "quote",
    name: "Quote",
    description: "Estimate with scope, price and sign-off",
    group: "Business",
    theme: "corporate",
    data: { company: "Brightline Builders", client: "Maya Patel", number: "Q-3301", date: "13 Sep 2026", valid: "13 Oct 2026" },
    settings: footer("Quote {{number}} · valid until {{valid}}"),
    blocks: () => [
      b("letterhead", { brand: "{{company}}", tagline: "Renovations and extensions", details: "quotes@brightline.build\n+1 415 555 0142" }),
      b("title", { eyebrow: "Quote {{number}}", title: "Kitchen renovation", subtitle: "Prepared for {{client}} on {{date}}" }),
      b("heading", { text: "Scope of work", level: 2 }),
      b("bullets", { items: ["Remove existing cabinets and worktops", "New electrical circuits for appliances", "Install oak cabinets and quartz worktops", "Tiling, painting and final clean"] }),
      b("table", { columns: ["Phase", "Duration", "Cost"], rows: [["Demolition", "3 days", "$2,100"], ["Electrical and plumbing", "5 days", "$6,400"], ["Installation", "8 days", "$18,900"], ["Finishing", "4 days", "$3,200"]] }),
      b("totals", { items: [{ label: "Subtotal", value: "$30,600" }, { label: "Contingency (5%)", value: "$1,530" }], totalLabel: "Estimated total", total: "$32,130" }),
      b("callout", { title: "Valid until {{valid}}", body: "Prices include materials and labour. A 20% deposit confirms your start date.", tone: "info" }),
      b("signature", { parties: [{ name: "{{company}}", role: "Contractor" }, { name: "{{client}}", role: "Client" }] }),
    ],
  },
  {
    id: "receipt",
    name: "Receipt",
    description: "Compact proof of payment",
    group: "Business",
    theme: "minimal",
    settings: { size: "A5", margin: "narrow" },
    data: { company: "Corner Café", number: "004812", date: "13 Sep 2026, 09:42" },
    blocks: () => [
      b("title", { eyebrow: "Receipt", title: "{{company}}", subtitle: "{{date}}", align: "center" }),
      b("divider", { variant: "dashed" }),
      b("table", { columns: ["Item", "Qty", "Total"], rows: [["Flat white", "2", "$9.00"], ["Almond croissant", "1", "$4.50"], ["Sparkling water", "1", "$3.00"]], striped: false }),
      b("totals", { items: [{ label: "Subtotal", value: "$16.50" }, { label: "Tip", value: "$2.00" }], totalLabel: "Paid by card", total: "$18.50" }),
      b("divider", { variant: "dashed" }),
      b("barcode", { data: "RC{{number}}", caption: "Receipt {{number}}" }),
      b("paragraph", { text: "Thanks for visiting. See you tomorrow.", align: "center", muted: true, size: "sm" }),
    ],
  },
  {
    id: "business-letter",
    name: "Business letter",
    description: "Formal letter on your letterhead",
    group: "Work",
    theme: "executive",
    data: { company: "Hartwell & Reed LLP", recipient: "Jordan Alvarez", date: "13 September 2026", sender: "Eleanor Hartwell" },
    blocks: () => [
      b("letterhead", { brand: "{{company}}", tagline: "Advisors since 1987", details: "1 Fleet Place, London\ninfo@hartwellreed.com" }),
      b("paragraph", { text: "{{date}}", muted: true }),
      b("paragraph", { text: "{{recipient}}\nOrion Logistics Ltd\n88 Canal Street, Manchester" }),
      b("paragraph", { text: "Dear {{recipient}}," }),
      b("paragraph", { text: "Thank you for meeting with us last week. As discussed, we are pleased to confirm our engagement to review your supplier contracts ahead of the renewal period." }),
      b("paragraph", { text: "Our review will cover **pricing terms**, **liability clauses** and **termination rights**, and we will share a written summary with recommended changes within three weeks." }),
      b("paragraph", { text: "Please let us know if there is anything else you would like us to consider." }),
      b("paragraph", { text: "Yours sincerely," }),
      b("signature", { parties: [{ name: "{{sender}}", role: "Partner, {{company}}" }], showDate: false }),
    ],
  },
  {
    id: "resume",
    name: "Resume",
    description: "One page with experience and skills",
    group: "Personal",
    theme: "orbit",
    settings: { margin: "narrow" },
    data: { name: "Sam Rivera", role: "Senior Product Designer", email: "sam@rivera.design" },
    blocks: () => [
      b("title", { eyebrow: "{{role}}", title: "{{name}}", subtitle: "{{email}} · Lisbon, Portugal · rivera.design" }),
      b("paragraph", { text: "Product designer with nine years of experience shipping **consumer and B2B software**. I turn fuzzy problems into simple, measurable products." }),
      b("heading", { text: "Experience", level: 3 }),
      b("timeline", {
        items: [
          { date: "2022 to now", title: "Lead Designer, Tidewave", body: "Led the redesign of the mobile banking app; activation up 23%." },
          { date: "2019 to 2022", title: "Product Designer, Loom & Co", body: "Built the design system used by 40 engineers across 6 teams." },
          { date: "2016 to 2019", title: "UX Designer, Fieldnote", body: "Designed onboarding and billing for a 200k-user SaaS." },
        ],
      }),
      b("heading", { text: "Skills", level: 3 }),
      b("badges", { items: ["Product strategy", "Interaction design", "Design systems", "Prototyping", "User research", "Figma"] }),
      b("heading", { text: "Education", level: 3 }),
      b("keyValue", { items: [{ label: "BA Communication Design", value: "University of Porto, 2016" }], columns: 1 }),
    ],
  },
  {
    id: "cover-letter",
    name: "Cover letter",
    description: "Warm, short and personal",
    group: "Personal",
    theme: "elegant",
    data: { name: "Sam Rivera", company: "Lumen Health", role: "Design Lead" },
    blocks: () => [
      b("title", { eyebrow: "Application for {{role}}", title: "{{name}}", subtitle: "" }),
      b("paragraph", { text: "Dear hiring team at {{company}}," }),
      b("paragraph", { text: "I have followed {{company}} since your first clinic app launched, and the care you put into making health information understandable is exactly why I want to join as {{role}}." }),
      b("paragraph", { text: "At Tidewave I led a team of four designers through a full redesign that lifted activation by 23%. I would love to bring that same mix of research, craft and patience to your patients." }),
      b("quote", { text: "Good design in healthcare is measured in anxiety removed.", cite: "A principle I design by" }),
      b("paragraph", { text: "Thank you for your time. I would be glad to talk whenever suits you." }),
      b("paragraph", { text: "Warm regards,\n**{{name}}**" }),
    ],
  },
  {
    id: "proposal",
    name: "Project proposal",
    description: "Goals, timeline, budget and sign-off",
    group: "Work",
    theme: "vivid",
    data: { company: "Studio Kite", client: "Greenleaf Markets", date: "September 2026" },
    settings: { ...footer("{{company}} for {{client}}"), header: { enabled: true, left: "Proposal", right: "{{date}}" } },
    blocks: () => [
      b("title", { eyebrow: "Proposal for {{client}}", title: "A loyalty app your shoppers will open every week", subtitle: "Prepared by {{company}}, {{date}}" }),
      b("stats", { items: [{ label: "Timeline", value: "14 weeks", note: "Oct to Jan" }, { label: "Investment", value: "$84k", note: "Fixed price" }, { label: "Team", value: "5 people", note: "Design and build" }] }),
      b("heading", { text: "What we will deliver", level: 2 }),
      b("numbered", { items: ["Research with 20 shoppers across three stores", "Interactive prototype tested in-store", "iOS and Android apps with points and offers", "Launch plan and staff training"] }),
      b("heading", { text: "Timeline", level: 2 }),
      b("timeline"),
      b("heading", { text: "Budget", level: 2 }),
      b("pieChart", { title: "Where the budget goes", data: [{ label: "Research", value: 15 }, { label: "Design", value: 30 }, { label: "Engineering", value: 45 }, { label: "Launch", value: 10 }] }),
      b("heading", { text: "Next steps", level: 2 }),
      b("checklist", { items: [{ text: "Review proposal", done: true }, { text: "Agree scope and budget", done: false }, { text: "Sign and schedule kick-off", done: false }] }),
      b("signature", { parties: [{ name: "{{company}}", role: "Studio" }, { name: "{{client}}", role: "Client" }] }),
    ],
  },
  {
    id: "report",
    name: "Quarterly report",
    description: "Key numbers, charts and highlights",
    group: "Work",
    theme: "corporate",
    data: { company: "Aurora Analytics", quarter: "Q3 2026" },
    settings: { header: { enabled: true, left: "{{company}}", right: "{{quarter}} report" }, footer: { enabled: true, left: "Confidential", pageNumbers: true } },
    blocks: () => [
      b("title", { eyebrow: "{{quarter}}", title: "Quarterly business review", subtitle: "Performance, customers and priorities for next quarter." }),
      b("stats"),
      b("heading", { text: "Revenue", level: 2 }),
      b("lineChart", { title: "Monthly recurring revenue ($k)", seriesName: "MRR", data: [{ label: "Apr", value: 310 }, { label: "May", value: 335 }, { label: "Jun", value: 362 }, { label: "Jul", value: 380 }, { label: "Aug", value: 404 }, { label: "Sep", value: 431 }] }),
      b("columns", { left: "**Highlights**\nEnterprise plan launched in July.\nThree new partners in APAC.", right: "**Watch list**\nSupport response time rose to 6h.\nTwo large renewals due in Q4.", ratio: "1:1" }),
      b("heading", { text: "Customers by region", level: 2 }),
      b("barChart", { title: "", data: [{ label: "North America", value: 1420 }, { label: "Europe", value: 1180 }, { label: "APAC", value: 610 }, { label: "LATAM", value: 270 }] }),
      b("heading", { text: "Priorities for next quarter", level: 2 }),
      b("progress", { items: [{ label: "Self-serve onboarding", value: 70 }, { label: "SOC 2 Type II", value: 45 }, { label: "Mobile app beta", value: 20 }] }),
    ],
  },
  {
    id: "meeting-minutes",
    name: "Meeting notes",
    description: "Attendees, decisions and actions",
    group: "Work",
    theme: "minimal",
    data: { team: "Platform team", date: "13 Sep 2026" },
    blocks: () => [
      b("title", { eyebrow: "Meeting notes", title: "{{team}} weekly", subtitle: "{{date}} · 30 minutes" }),
      b("keyValue", { items: [{ label: "Attendees", value: "Ana, Ben, Chloe, Dev" }, { label: "Facilitator", value: "Chloe" }, { label: "Next meeting", value: "20 Sep 2026" }] }),
      b("heading", { text: "Decisions", level: 3 }),
      b("bullets", { items: ["Move the release to Thursday to include the billing fix", "Pause the analytics migration until October"] }),
      b("heading", { text: "Action items", level: 3 }),
      b("table", { columns: ["Action", "Owner", "Due"], rows: [["Write rollback plan", "Ben", "15 Sep"], ["Update status page copy", "Ana", "16 Sep"], ["Book load test window", "Dev", "18 Sep"]], striped: false, numericLast: false }),
      b("callout", { title: "Blocked", body: "Waiting on security review for the new SSO provider.", tone: "warning" }),
    ],
  },
  {
    id: "certificate",
    name: "Certificate",
    description: "Landscape award with signatures",
    group: "Events",
    theme: "elegant",
    settings: { orientation: "landscape", margin: "wide" },
    data: { recipient: "Priya Shah", course: "Advanced Data Visualisation", date: "13 September 2026" },
    blocks: () => [
      b("spacer", { size: 12 }),
      b("title", { eyebrow: "Certificate of completion", title: "{{recipient}}", subtitle: "has successfully completed {{course}}", align: "center" }),
      b("divider", { variant: "accent", space: "lg" }),
      b("paragraph", { text: "Awarded on {{date}} in recognition of outstanding work across twelve weeks of study.", align: "center", muted: true }),
      b("spacer", { size: 24 }),
      b("signature", { parties: [{ name: "Dr. Helen Moore", role: "Programme Director" }, { name: "Marcus Lee", role: "Head of Faculty" }], showDate: false }),
    ],
  },
  {
    id: "ticket",
    name: "Event ticket",
    description: "Admission pass with QR code",
    group: "Events",
    theme: "vivid",
    settings: { size: "A5", orientation: "landscape", margin: "narrow" },
    data: { event: "Design Systems Summit", attendee: "Alex Kim", seat: "B-14", code: "DSS26-8841" },
    blocks: () => [
      b("title", { eyebrow: "Admit one", title: "{{event}}", subtitle: "Friday 16 October 2026 · Doors 8:30" }),
      b("columns", { left: "**Attendee**\n{{attendee}}\n\n**Venue**\nThe Forum, Hall 2\nLisbon", right: "**Seat**\n{{seat}}\n\n**Ticket**\n{{code}}", ratio: "1:1" }),
      b("qr", { data: "{{code}}", size: 96, caption: "Show at the entrance", align: "right" }),
    ],
  },
  {
    id: "packing-slip",
    name: "Packing slip",
    description: "Order contents with a barcode",
    group: "Business",
    theme: "blueprint",
    data: { order: "ORB-2026-0042", company: "Tallow Supply", client: "Jamie Ortiz" },
    blocks: () => [
      b("letterhead", { brand: "{{company}}", tagline: "Packing slip", details: "Order {{order}}\nShipped 13 Sep 2026" }),
      b("addresses", { fromLabel: "Ship from", from: "{{company}}\nUnit 4, Dock Road\nRotterdam, NL", toLabel: "Ship to", to: "{{client}}\n19 Rue des Lilas\nLyon, FR" }),
      b("table", { columns: ["SKU", "Item", "Qty"], rows: [["TS-101", "Hand-poured candle, cedar", "2"], ["TS-205", "Linen tea towel set", "1"], ["TS-330", "Ceramic diffuser", "1"]], striped: true, numericLast: true }),
      b("barcode", { data: "{{order}}", caption: "Order {{order}}" }),
      b("finePrint", { text: "Something missing? Email orders@tallow.supply within 30 days." }),
    ],
  },
  {
    id: "lesson-plan",
    name: "Lesson plan",
    description: "Objectives, activities and materials",
    group: "Personal",
    theme: "forest",
    data: { subject: "Ecosystems", grade: "Year 6", teacher: "Ms. Okafor" },
    blocks: () => [
      b("title", { eyebrow: "{{grade}} · Science", title: "{{subject}}: food chains", subtitle: "60 minutes · {{teacher}}" }),
      b("heading", { text: "Learning objectives", level: 3 }),
      b("bullets", { items: ["Explain producers, consumers and decomposers", "Build a food chain from a local habitat", "Predict what happens when one link is removed"] }),
      b("heading", { text: "Plan", level: 3 }),
      b("table", { columns: ["Time", "Activity"], rows: [["10 min", "Warm-up: who eats what?"], ["20 min", "Group task: build a pond food chain"], ["20 min", "Share and discuss changes"], ["10 min", "Exit ticket"]], striped: true, numericLast: false }),
      b("heading", { text: "Materials", level: 3 }),
      b("checklist", { items: [{ text: "Habitat picture cards", done: true }, { text: "String and pegs", done: true }, { text: "Exit ticket sheets", done: false }] }),
      b("callout", { title: "Differentiation", body: "Provide word banks for EAL learners; stretch groups add a second habitat.", tone: "success" }),
    ],
  },
  {
    id: "press-release",
    name: "Press release",
    description: "Announcement with quote and contact",
    group: "Work",
    theme: "professional",
    data: { company: "Solace Energy", city: "Austin", date: "13 September 2026" },
    settings: { header: { enabled: true, left: "For immediate release", right: "{{date}}" } },
    blocks: () => [
      b("title", { eyebrow: "News", title: "{{company}} opens its largest community solar farm", subtitle: "The 40 MW site will power 9,000 homes across central Texas." }),
      b("paragraph", { text: "**{{city}}, {{date}}.** {{company}} today opened the Bluebonnet solar farm, its largest community project to date, giving local households access to clean energy without installing panels at home." }),
      b("quote", { text: "Every household should be able to choose clean power, whether they own a roof or not.", cite: "Rosa Delgado, CEO of {{company}}" }),
      b("stats", { items: [{ label: "Capacity", value: "40 MW", note: "" }, { label: "Homes powered", value: "9,000", note: "" }, { label: "Local jobs", value: "120", note: "" }] }),
      b("heading", { text: "About {{company}}", level: 3 }),
      b("paragraph", { text: "{{company}} builds and operates community solar across the southern United States.", muted: true }),
      b("keyValue", { items: [{ label: "Press contact", value: "press@solace.energy" }, { label: "Phone", value: "+1 512 555 0199" }] }),
    ],
  },
  {
    id: "event-agenda",
    name: "Event agenda",
    description: "Schedule with speakers and venue",
    group: "Events",
    theme: "modern",
    data: { event: "Product Leaders Meetup", date: "Thursday 8 October 2026" },
    blocks: () => [
      b("title", { eyebrow: "Agenda", title: "{{event}}", subtitle: "{{date}} · The Old Library, Bristol" }),
      b("timeline", {
        items: [
          { date: "18:00", title: "Doors and drinks", body: "Registration in the foyer." },
          { date: "18:30", title: "Talk: Shipping without roadmaps", body: "Nadia Brooks, VP Product at Fernway" },
          { date: "19:15", title: "Panel: Pricing experiments", body: "Three founders on what worked and what didn't." },
          { date: "20:00", title: "Networking", body: "Food served until 21:00." },
        ],
      }),
      b("card", { title: "Getting there", body: "Five minutes from Temple Meads station. Step-free access through the side entrance.", variant: "outline" }),
      b("qr", { data: "https://example.com/rsvp", caption: "RSVP and updates", size: 72 }),
    ],
  },
];

/** Creates a new document from a preset. */
export function docFromPreset(preset: Preset): CreatorDoc {
  const base = structuredClone(DEFAULT_SETTINGS);
  const settings: DocSettings = { ...base, ...preset.settings };
  return {
    version: 1,
    id: crypto.randomUUID(),
    name: preset.id === "blank" ? "Untitled document" : preset.name,
    theme: preset.theme,
    accent: null,
    settings,
    data: { ...preset.data },
    blocks: preset.blocks(),
    updatedAt: Date.now(),
  };
}
